### ISSUE TITLE
YAML configuration

### ISSUE THREAD

**Issue by laoshanxi** [laoshanxi/app-mesh#270]
```yaml
# YAML example for cross-application usage

# Configuration section
config:
  app_name: MyApp
  debug_mode: true
  log_level: 2

# Database configuration
database:
  host: localhost
  port: 5432
  username: myuser
  password: mypassword
  database_name: mydb

# API settings
api:
  endpoint: /api/v1
  timeout: 5000

# List of users
users:
  - name: John Doe
    age: 30
    email: johndoe@example.com
  - name: Jane Smith
    age: 25
    email: janesmith@example.com

# Default values for optional fields
defaults:
  timeout: 3000
  max_attempts: 3
```
