### ISSUE TITLE
Build macOS package

### ISSUE THREAD

**Issue by laoshanxi** [laoshanxi/app-mesh#356]
PKG (Installer Package)
Best for: Installing applications that need system-wide configurations, CLI tools, or background services.
Advantages:
Automates installation of files to system locations (e.g., /usr/local/bin, /Library/LaunchDaemons).
Can execute pre/post-installation scripts.
Suitable for privileged operations (e.g., setting up launch daemons).
Provides native macOS installer experience.
Steps to Create a PKG:
Prepare File Layout:

Create a directory structure resembling the installation paths:
```bash
./package_root/
├── usr/local/bin/myapp       # Your CLI binary
├── Library/LaunchDaemons/com.example.myapp.plist
```
Create a LaunchDaemon for macOS (Equivalent to systemd):

Example com.example.myapp.plist:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.example.myapp</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/myapp</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>
```
Use pkgbuild:

Create the .pkg using macOS's pkgbuild:
```bash
pkgbuild \
  --root ./package_root \
  --identifier com.example.myapp \
  --version 1.0.0 \
  --install-location / \
  myapp.pkg
```
(Optional) Include Pre/Post Scripts:

To add system setup steps (e.g., registering the daemon), include scripts:
```bash
pkgbuild \
  --root ./package_root \
  --identifier com.example.myapp \
  --version 1.0.0 \
  --install-location / \
  --scripts ./scripts \
  myapp.pkg
```
Place preinstall and postinstall scripts in the ./scripts/ directory.

**Comment by laoshanxi** [comment]
macOS Github action

Leverage a CI/CD platform that provides macOS build environments, such as GitHub Actions, CircleCI, or Travis CI.

Steps:
Set Up a macOS Workflow: Example using GitHub Actions:

```yaml
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install cmake
          brew install pkg-config

      - name: Build
        run: |
          mkdir build && cd build
          cmake .. && make

      - name: Package
        run: |
          mkdir dist
          pkgbuild --root build/output --identifier com.example.myapp --version 1.0.0 dist/myapp.pkg
```
Trigger the Workflow: Run the macOS-specific build process when needed, producing .pkg or .dmg artifacts.
